### ISSUE TITLE
Remove fedora 18 info

### ISSUE THREAD

**Issue by oguya** [oguya/mirror.mjanja.co.ke#1]
Seems like Fedora 18 is deprecated[1] by upstream mirrors, therefore, I think we should remove all info related to it on this repo.
1. https://lists.fedoraproject.org/pipermail/announce/2014-January/003194.html

**Comment by alanorth** [comment]
Remove 18, 19, and 20! Indeed!

https://fedoraproject.org/wiki/End_of_life
